### ISSUE TITLE
POP3 Connection Failed

### ISSUE THREAD

**Issue by xianzhe18** [Webklex/php-imap#135]
[Stackoverflow Question](https://stackoverflow.com/questions/67562683/pop3-connection-failed)

I installed email server on my local machine and get emails from it using this package. I enabled both of IMAP (993) and POP3 (995). But POP3 doesn't work, while IMAP does.
Please help me to get POP3 worked.

Code is as follows:
```php
$cm = new ClientManager();
$oClient = $cm->make([
    'host' => 'localhost',
    'port' => 995,
    'encryption' => 'ssl',
    'validate_cert' => false,
    'username' => $account->account,
    'password' => $account->password,
    'protocol' => 'pop3',
    'authentication' => 'base64',
    'masks' => [
        'message' => \Webklex\PHPIMAP\Support\Masks\MessageMask::class,
        'attachment' => \Webklex\PHPIMAP\Support\Masks\AttachmentMask::class
    ]
]);
$oClient->connect();
```

Error is as follows:
```
[2021-05-04 10:16:49] development.ERROR: connection setup failed  
[2021-05-04 10:16:49] development.ERROR: File: <APP_PATH>\vendor\webklex\php-imap\src\Client.php  
[2021-05-04 10:16:49] development.ERROR: Line: 378  
[2021-05-04 10:16:49] development.ERROR: #0 <APP_PATH>\vendor\webklex\php-imap\src\Client.php(358): Webklex\PHPIMAP\Client->authenticate()
#1 <APP_PATH>\app\Traits\WebklexEmailTrait.php(58): Webklex\PHPIMAP\Client->connect()
#2 <APP_PATH>\app\Console\Commands\WebklexCheck.php(65): App\Console\Commands\WebklexCheck->checkInbox(Object(App\Models\EmailAccount))
#3 <APP_PATH>\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Console\Commands\WebklexCheck->handle()
#4 <APP_PATH>\vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 <APP_PATH>\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#6 <APP_PATH>\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 <APP_PATH>\vendor\laravel\framework\src\Illuminate\Container\Container.php(610): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 <APP_PATH>\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call(Array)
#9 <APP_PATH>\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 <APP_PATH>\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 <APP_PATH>\vendor\symfony\console\Application.php(971): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 <APP_PATH>\vendor\symfony\console\Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\WebklexCheck), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 <APP_PATH>\vendor\symfony\console\Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 <APP_PATH>\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 <APP_PATH>\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 <APP_PATH>\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main}  
```

**Comment by xianzhe18** [comment]
I found problem myself.

At Line `82` in `webklex/php-imap/src/Connection/Protocols/LegacyProtocol.php`, option `IMAP::OP_READONLY` is the problem. 
According to [PHP documentation](https://www.php.net/manual/en/function.imap-open.php), POP3 doesn't support `readonly` flag.

**Comment by 91Abdullah** [comment]
> I found problem myself.
> 
> At Line `82` in `webklex/php-imap/src/Connection/Protocols/LegacyProtocol.php`, option `IMAP::OP_READONLY` is the problem.
> According to [PHP documentation](https://www.php.net/manual/en/function.imap-open.php), POP3 doesn't support `readonly` flag. It means no one can connect POP3 by using this package, and it must be clarified in README file, e.g., _**This package supports only IMAP, not POP3 or others**_.

@xianzhe18  did you find solution of this?

**Comment by Djurdjijan** [comment]
@91Abdullah  
in imap.php set IMAP_PROTOCOL to pop3 :)
