### ISSUE TITLE
[BUG] Webklex\PHPIMAP\Exceptions\RuntimeException: idle failed

### ISSUE THREAD

**Issue by dokicro** [Webklex/php-imap#296]
**Describe the bug**
After 10-30minutes of running custom idle command per instructions (https://www.php-imap.com/frameworks/laravel/commands) I get the following error:

```
[2022-10-11 13:30:58] production.ERROR: Webklex\PHPIMAP\Exceptions\RuntimeException: idle failed in /var/www/laravel/vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php:1055
Stack trace:
#0 /var/www/laravel/vendor/webklex/php-imap/src/Folder.php(402): Webklex\PHPIMAP\Connection\Protocols\ImapProtocol->idle()
#1 /var/www/laravel/app/Console/Commands/PayTicketIdleCommand.php(81): Webklex\PHPIMAP\Folder->idle()
#2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Console\Commands\PayTicketIdleCommand->handle()
#3 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#5 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#6 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#7 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#8 /var/www/laravel/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#9 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#10 /var/www/laravel/vendor/symfony/console/Application.php(1015): Illuminate\Console\Command->run()
#11 /var/www/laravel/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#12 /var/www/laravel/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#13 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#14 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#15 /var/www/laravel/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#16 {main}
```

I am connected to Gmail business account

I played with debug mode and here is the output:

```
<< TAG3 OK [READ-WRITE] INBOX selected. (Success)
>> TAG4 IDLE
<< + idling
<< * 1 EXPUNGE
>> DONE
<< * 1 EXISTS
>> TAG5 IDLE
<< TAG4 OK IDLE terminated (Success)
>> DONE
<< + idling
>> TAG6 IDLE
<< TAG5 OK IDLE terminated (Success)

   Webklex\PHPIMAP\Exceptions\RuntimeException

  idle failed

  at vendor/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php:1055
    1051▕      */
    1052▕     public function idle() {
    1053▕         $this->sendRequest("IDLE");
    1054▕         if (!$this->assumedNextLine('+ ')) {
  ➜ 1055▕             throw new RuntimeException('idle failed');
    1056▕         }
    1057▕     }
    1058▕
    1059▕     /**

      +1 vendor frames
  2   app/Console/Commands/InfoTicketIdleCommand.php:81
      Webklex\PHPIMAP\Folder::idle()

      +13 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
>> TAG7 LOGOUT
<< + idling
<< TAG6 BAD Could not parse command
```

The problem could be that TAG5 came after TAG6 ?

**Desktop / Server (please complete the following information):**
 - OS: Cenots 7
- PHP: PHP 8.1.9
 - Version "webklex/laravel-imap": "^4.0",

**Comment by Webklex** [comment]
Hi @dokicro ,
many thanks for your report. Please update to v5.1 and give it another try.
If you are currently using an older version below v5.0, please read the breaking changes leading up to v5.1 before upgrading.

Best regards,

**Comment by dokicro** [comment]
@Webklex unfortunately I am using `google-api` for communication this days, so I cant test it :/

Should we close this issue?
