### ISSUE TITLE
IMAP Gmail - connection setup failed

### ISSUE THREAD

**Issue by igordeveloper** [Webklex/php-imap#322]
Hello.

I'm trying to use the library to connect my gmail account, but i'm receiving the message error below.
```

Thu Nov 10 15:20:15 2022] 127.0.0.1:57154 Accepted
[Thu Nov 10 15:20:16 2022] got an extra server challenge: eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==

[Thu Nov 10 15:20:16 2022] got failure response: NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)

[Thu Nov 10 15:20:16 2022] PHP Fatal error:  Uncaught Webklex\PHPIMAP\Exceptions\AuthFailedException in /home/igor/projects/php-imap/src/Client.php:385
Stack trace:
#0 /home/igor/projects/php-imap/src/Client.php(371): Webklex\PHPIMAP\Client->authenticate()
#1 /home/igor/projects/php-imap/index.php(19): Webklex\PHPIMAP\Client->connect()
#2 {main}

Next Webklex\PHPIMAP\Exceptions\ConnectionFailedException: connection setup failed in /home/igor/projects/php-imap/src/Client.php:391
Stack trace:
#0 /home/igor/projects/php-imap/src/Client.php(371): Webklex\PHPIMAP\Client->authenticate()
#1 /home/igor/projects/php-imap/index.php(19): Webklex\PHPIMAP\Client->connect()
#2 {main}
  thrown in /home/igor/projects/php-imap/src/Client.php on line 391
[Thu Nov 10 15:20:16 2022] 127.0.0.1:53416 [200]: GET / - Uncaught Webklex\PHPIMAP\Exceptions\AuthFailedException in /home/igor/projects/php-imap/src/Client.php:385
Stack trace:
#0 /home/igor/projects/php-imap/src/Client.php(371): Webklex\PHPIMAP\Client->authenticate()
#1 /home/igor/projects/php-imap/index.php(19): Webklex\PHPIMAP\Client->connect()
#2 {main}

Next Webklex\PHPIMAP\Exceptions\ConnectionFailedException: connection setup failed in /home/igor/projects/php-imap/src/Client.php:391
Stack trace:
#0 /home/igor/projects/php-imap/src/Client.php(371): Webklex\PHPIMAP\Client->authenticate()
#1 /home/igor/projects/php-imap/index.php(19): Webklex\PHPIMAP\Client->connect()
#2 {main}
  thrown in /home/igor/projects/php-imap/src/Client.php on line 391
```

My code:

```
use Webklex\PHPIMAP\ClientManager;

$cm = new ClientManager($options = []);

$client = $cm->make([
    'host' => 'imap.gmail.com',
    'port' => 993,
    'encryption' => 'ssl',
    'validate_cert' => true,
    'username' => 'username',
    'password' => 'password',
    'authentication' => 'oauth',
]);
$client->connect();
$folders = $client->getFolders('INBOX');
``
```

Could you please help me if i did something wrong in the configuration?
Thank you.

igor.

**Comment by Webklex** [comment]
Hi @igordeveloper ,
please checkout this example: https://www.php-imap.com/examples/oauth

You'll need to provide either a dedicated app password or use the google auth flow to obtain a valid access token.

Best regards & happy coding,

**Comment by igordeveloper** [comment]
> You'll need to provide either a dedicated app password or use the google auth flow to obtain a valid access token.

Hi.

I'll check it.

Thank you for the quick reply,
