### ISSUE TITLE
Move Inbox.read is not working on Outlook office365 mail. Getting exception Error

### ISSUE THREAD

**Issue by thanjeys** [Webklex/php-imap#375]
**Describe the bug**

**Used config**
Please provide the used config, if you are not using the package default config.

**Code to Reproduce**
The troubling code section which produces the reported bug.
```php
echo "Bug";
```

**Expected behavior**

**Screenshots**

**Desktop / Server (please complete the following information):**
- OS: [e.g. Debian 10] Windows
- PHP: [e.g. 5.5.9] 8.0
- Version [e.g. v2.3.1] 5.0
- Provider [e.g. Gmail, Outlook, Dovecot] Outlook

**Additional context**

Hi, 

I connected Office365 with Oauth method using Refresh token.  Everything works good except INBOX.read move method only.
```php
$folder = $client->getFolder('INBOX');
        
        $today = date('Y-m-d');
        $subractedDay = date('d.m.Y', strtotime($today. ' - 1 days'));

        $messages = $folder->query()->since('16.02.2023')->unseen()->get();
        
        foreach($messages as $message){
            echo $message->getSubject().'<br />';
            echo 'Attachments: '.$message->getAttachments()->count().'<br />';
            echo $message->getHTMLBody();
            
            // $client->openFolder('INBOX.read'); 

            // Move the current Message to 'INBOX.read'
            if($message->move('INBOX.read') == true){
                echo 'Message has been moved';
            }else{
                echo 'Message could not be moved';
            }
            echo 'Email DONE';
        }
```

Fatal error: Uncaught Webklex\PHPIMAP\Exceptions\ResponseException: **Command failed to process: Causes: - request failed - Empty response Error occurred** in D:\xampp8\htdocs\imapauth\php-imap\src\Exceptions\ResponseException.php:53 Stack trace: #0 D:\xampp8\htdocs\imapauth\php-imap\src\Connection\Protocols\Response.php(310): Webklex\PHPIMAP\Exceptions\ResponseException::make(Object(Webklex\PHPIMAP\Connection\Protocols\Response), false) #1 D:\xampp8\htdocs\imapauth\php-imap\src\Connection\Protocols\Response.php(301): Webklex\PHPIMAP\Connection\Protocols\Response->validate() #2 D:\xampp8\htdocs\imapauth\php-imap\src\Message.php(1043): Webklex\PHPIMAP\Connection\Protocols\Response->validatedData() #3 D:\xampp8\htdocs\imapauth\mailbox.php(77): Webklex\PHPIMAP\Message->move('INBOX.read') #4 {main} thrown in D:\xampp8\htdocs\imapauth\php-imap\src\Exceptions\ResponseException.php on line 53

Please help me to solve this problem. 

Thanks

**Comment by thanjeys** [comment]
Hi,

I solved this issue using  this code in loop.           

$message->setFlag('SEEN');

Thanks
