### ISSUE TITLE
Need help: Copy a message sent via SMTP to "Sent" folder by IMAP

### ISSUE THREAD

**Issue by PhilippGrashoff** [Webklex/php-imap#485]
Hey there,

I need a push in the right direction. Due to problems with STARTTLS in the currently unmaintained imap extention of php, I want to switch to webklex php-imap.
What I want to do is rather easy:
I use PHPMailer to send a message via SMTP. After doing this, I want to copy the sent message to the Sent folder by IMAP. My code with php's imap extention was quite simple:

```php
        try {
            $imapStream = imap_open(
                $imap_mailbox,
                $this->emailAccount->get('user'),
                $this->emailAccount->get('password')
            );
            $this->appendedByIMAP = imap_append($imapStream, $imap_mailbox, $this->getSentMIMEMessage());
            ....
```

When porting this to webklex php-imap, I am facing the issue that I need to create a Message. This message needs a UID. My code so far looks like:

```php
  $client = $this->createImapClient();
  $message = new Message(IMAP::ST_UID, null, $client);
  ....

 protected function createImapClient(): Client
    {
        $cm = new ClientManager();
        $client = $cm->make(
            [
                'host' => $this->emailAccount->get('imap_host'),
                'port' => $this->emailAccount->get('imap_port'),
                'encryption' => $this->emailAccount->get('imap_port') == 993 ? 'ssl' : 'starttls',
                'validate_cert' => true,
                'username' => $this->emailAccount->get('user'),
                'password' => $this->emailAccount->get('password'),
                'protocol' => 'imap'
            ]
        );

        $client->connect();
        $client->openFolder($this->emailAccount->get('imap_sent_folder'));

        return $client;
    }
```

When executing this, I get an exception with the error message "message number not found" with the relevant stack trace:
```
#0 /var/www/html/PMRAtk/vendor/webklex/php-imap/src/Message.php(1375): Webklex\PHPIMAP\Connection\Protocols\ImapProtocol->getMessageNumber()
#1 /var/www/html/PMRAtk/vendor/webklex/php-imap/src/Message.php(1426): Webklex\PHPIMAP\Message->setUid()
#2 /var/www/html/PMRAtk/vendor/webklex/php-imap/src/Message.php(211): Webklex\PHPIMAP\Message->setSequenceId()
#3 /var/www/html/PMRAtk/src/Data/Email/PHPMailer.php(124): Webklex\PHPIMAP\Message->__construct()
```

So for my use case, I would (at least to my current understanding), need to create a Message without a UID, as this could only be assigned after copying the message to the email server...

Could someone point me in the right direction how to proceed?

Thanks & best regards

**Comment by PhilippGrashoff** [comment]
The solution is utterly simple. My misconception was that a Message object was needed for this - it isn't.
Here is a working solution:

```php
           ...
           $client = $this->createImapClient();
           $client->connection->appendMessage(
                $this->emailAccount->get('imap_sent_folder'),
                $this->getSentMIMEMessage()
            );
            ...

    protected function createImapClient(): Client
    {
        $cm = new ClientManager();
        $client = $cm->make(
            [
                'host' => $this->emailAccount->get('imap_host'),
                'port' => $this->emailAccount->get('imap_port'),
                'encryption' => $this->emailAccount->get('imap_port') == 993 ? 'ssl' : 'starttls',
                'validate_cert' => true,
                'username' => $this->emailAccount->get('user'),
                'password' => $this->emailAccount->get('password'),
                'protocol' => 'imap'
            ]
        );

        $client->connect();

        return $client;
    }

```
