### ISSUE TITLE
Can not delete message; get exception also it is deleted from INBOX

### ISSUE THREAD

**Issue by napengam** [Webklex/php-imap#512]
Deleting one  email from gmail INBOX throws exception, but it is actualy deleted from INBOX

´´´
[31-Aug-2024 20:38:39 Europe/Berlin] PHP Fatal error:  Uncaught Webklex\PHPIMAP\Exceptions\ResponseException: Command failed to process:
Causes:
	- Empty response
Commands send:
	TAG11 UID FETCH 842 (FLAGS)\r\n
Responses received:
	TAG11 OK Success\r\n
Error occurred in F:\xampp-htdocs\projectCore\vendor\webklex\php-imap\src\Exceptions\ResponseException.php:53
Stack trace:
#0 F:\xampp-htdocs\projectCore\vendor\webklex\php-imap\src\Connection\Protocols\Response.php(318): Webklex\PHPIMAP\Exceptions\ResponseException::make(Object(Webklex\PHPIMAP\Connection\Protocols\Response), true)
#1 F:\xampp-htdocs\projectCore\vendor\webklex\php-imap\src\Connection\Protocols\Response.php(308): Webklex\PHPIMAP\Connection\Protocols\Response->validate()
#2 F:\xampp-htdocs\projectCore\vendor\webklex\php-imap\src\Message.php(585): Webklex\PHPIMAP\Connection\Protocols\Response->validatedData()
#3 F:\xampp-htdocs\projectCore\vendor\webklex\php-imap\src\Message.php(1254): Webklex\PHPIMAP\Message->parseFlags()
#4 F:\xampp-htdocs\projectCore\vendor\webklex\php-imap\src\Message.php(1194): Webklex\PHPIMAP\Message->setFlag('\\Deleted')
#5 F:\xampp-htdocs\projectCore\test\klex.php(62): Webklex\PHPIMAP\Message->delete(false)
#6 {main}
  thrown in F:\xampp-htdocs\projectCore\vendor\webklex\php-imap\src\Exceptions\ResponseException.php on line 53
´´´

**Comment by IulianMoldovanu** [comment]
I encountered the same issue and resolved it by using `$message->move('[Gmail]/Trash')` instead of `$message->delete()`.

**Comment by napengam** [comment]
I wrapped a try catch around the delete() now it works without any hickups:-)

**Comment by sertancayci-jf** [comment]
@napengam i tried try catch but still take belowed error. Also i tried `$message->delete(); ` , `$message->delete(true) ` or `$message->delete($expunge = true) `. I always take same error Any help? 

> Command failed to process:
> Causes:
> 	- Empty response

` $foundedMessage = null;
        foreach($messages as $message){
            echo "Message: " . PHP_EOL;
            echo "Subject: " . $message->getSubject() . PHP_EOL;
            echo "UID: " . $message->getUid() . PHP_EOL;
            echo "Timestamp: " . $message->getDate()  . PHP_EOL;

            if (trim($message->getSubject()) === trim($subject)) {
                $foundedMessage = $message;
                echo "Email found." . PHP_EOL;
                try {
                    $message->setFlag("Deleted");
                    echo "Email marked as deleted." . PHP_EOL;
                } catch (\Exception $e) {
                    // Log the error or handle it appropriately
                    echo "Failed to delete message: " . $e->getMessage();
                }
                break;
            }

        }`
        
        
        <<  FLAGS (\Seen))
<< * 1 FETCH (UID 12345 FLAGS (\Seen))
<< TAG7 OK Success
>> TAG8 UID STORE 12345:12345 -FLAGS.SILENT (\Seen)

<< * 1 FETCH (UID 12345 FLAGS ())
<< TAG8 OK Success
>> TAG9 UID FETCH 12345 (FLAGS)

<< * 1 FETCH (UID 12345 FLAGS ())
<< TAG9 OK Success
Message: 
Subject: "subject"
UID: 12345
Timestamp: 2025-01-02 09:36:23
Email found.
>> TAG10 UID STORE 12345:12345 +FLAGS.SILENT (\Deleted)

<< * 1 EXPUNGE
<< * 0 EXISTS
<< TAG10 OK Success
>> TAG11 UID FETCH 12345 (FLAGS)

<< TAG11 OK Success
Failed to delete message: Command failed to process:
Causes:
	- Empty response
Commands send:
	TAG11 UID FETCH 12345 (FLAGS)\r\n
Responses received:
	TAG11 OK Success\r\n
Error occurred>> TAG12 EXPUNGE

<< TAG12 OK Success
>> TAG13 LOGOUT

<< * BYE LOGOUT Requested
<< TAG13 OK 73 good day (Success)
